### ISSUE TITLE
Suggestions for mobile?

### ISSUE THREAD

**Issue by benjick** [konstantinmuenster/lexical-floating-menu#7]
Hey!

Thanks for making this plugin, it works great. I just have one question, how do I solve this issue on mobile where the native contextmenu is shown above the floating menu?

![image](https://github.com/konstantinmuenster/lexical-floating-menu/assets/430872/8e6d87d2-12f4-45bc-ad39-b8a7103dc556)
This is on selection

![image](https://github.com/konstantinmuenster/lexical-floating-menu/assets/430872/693c6fb5-f57b-4db6-8f1d-f71a6dea1d42)
Here is when I have moved the native contextmenu, but I'm not sure my average visitor will be aware of this

I tried setting `onContextMenu={(e) => e.preventDefault()}` but that made me not be able to select text at all

Any suggestions?

Cheers
Max

**Comment by konstantinruge** [comment]
Hey @benjick! 

Great question. As far as I know there isn't any reliable way of doing this across browsers. I usually went the same route as you did: repositioning both menus so that one opened above and the other one below.

Hope that helps (although it's probably not the answer you wanted to hear 😉).

**Comment by benjick** [comment]
Thanks! I figured so, I couldn't find anything of my own but it was worth a shot!

Btw, can the popup be triggered when `editable: false`?

**Comment by konstantinruge** [comment]
> Btw, can the popup be triggered when `editable: false`?

Yep, that should still work despite the flag.
